language: java
jdk: oraclejdk11

script: mvn -e verify

notifications:
  email:
    recipients:
      - khdilyara@rambler.ru
    on_failure: always
    on_success: change

deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: cookbook-2020